name: Feature Request
description: Suggest a new feature or improvement for HedgieMate
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve HedgieMate! Please describe your feature request in detail.

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platform(s)
      description: Which platform(s) would benefit from this feature?
      options:
        - label: iPhone
        - label: iPad
        - label: Apple Watch
        - label: Mac
        - label: Vision Pro
        - label: Home Screen Widgets

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the app does this relate to?
      options:
        - Dashboard
        - Charging
        - Drives/Trips
        - Statistics/Charts
        - Battery Health
        - Timeline
        - Widgets
        - Settings
        - Apple Watch
        - UI/UX
        - Performance
        - Localization
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: "I also thought about..."
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have any mockups, sketches, or examples from other apps, please share
      placeholder: "Drag and drop images here"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my experience
        - Important for my use case
        - Critical - blocking my workflow
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
    validations:
      required: false
